repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*\\.md$"
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.24
    hooks:
      - id: helmlint
